// MIDU — three premium-minimal directions
// Each theme is a complete visual system the prototype consumes.

const MIDU_THEMES = {
  editorial: {
    key: 'editorial',
    label: 'A · Editorial',
    blurb: 'Magazine-quiet. Serif display, generous whitespace.',
    bg: '#ffffff',
    surface: '#ffffff',
    surfaceAlt: '#f6f4ef',
    text: '#0a0a09',
    textMuted: '#76726a',
    line: '#e8e5dc',
    lineStrong: '#0a0a09',
    accent: '#0a0a09',
    btnBg: '#0a0a09',
    btnText: '#ffffff',
    chipBg: '#f3f0e8',
    fontDisplay: '"Cormorant Garamond", "Cormorant", Georgia, serif',
    fontBody: '"Manrope", system-ui, sans-serif',
    fontMono: '"Manrope", system-ui, sans-serif',
    h1Size: 92, h1Weight: 400, h1Tracking: -0.02,
    h2Size: 44, h2Weight: 400,
    eyebrow: { size: 11, weight: 500, tracking: 0.22, upper: true, font: 'body' },
    productNameWeight: 400,
    cardRadius: 0,
    btnRadius: 0,
    showRules: false,
    productPad: 0,
  },
  grid: {
    key: 'grid',
    label: 'B · Grid',
    blurb: 'Technical & structural. Thin rules, mono labels.',
    bg: '#fafaf6',
    surface: '#fafaf6',
    surfaceAlt: '#f0eee7',
    text: '#15140f',
    textMuted: '#6a665a',
    line: '#1a1915',
    lineStrong: '#1a1915',
    accent: '#cf4520',
    btnBg: '#15140f',
    btnText: '#fafaf6',
    chipBg: 'transparent',
    fontDisplay: '"Space Grotesk", system-ui, sans-serif',
    fontBody: '"Space Grotesk", system-ui, sans-serif',
    fontMono: '"JetBrains Mono", ui-monospace, monospace',
    h1Size: 72, h1Weight: 500, h1Tracking: -0.03,
    h2Size: 34, h2Weight: 500,
    eyebrow: { size: 10, weight: 500, tracking: 0.18, upper: true, font: 'mono' },
    productNameWeight: 500,
    cardRadius: 0,
    btnRadius: 0,
    showRules: true,
    productPad: 14,
  },
  boutique: {
    key: 'boutique',
    label: 'C · Boutique',
    blurb: 'Warm cream, gentle serif accent, soft contrast.',
    bg: '#f1ece2',
    surface: '#f1ece2',
    surfaceAlt: '#e7e0d0',
    text: '#2a241c',
    textMuted: '#857a68',
    line: '#dcd1bc',
    lineStrong: '#3a3328',
    accent: '#7d2a2a',
    btnBg: '#2a241c',
    btnText: '#f1ece2',
    chipBg: '#e7e0d0',
    fontDisplay: '"Tenor Sans", "Cormorant", Georgia, serif',
    fontBody: '"Outfit", system-ui, sans-serif',
    fontMono: '"Outfit", system-ui, sans-serif',
    h1Size: 76, h1Weight: 400, h1Tracking: -0.01,
    h2Size: 38, h2Weight: 400,
    eyebrow: { size: 11, weight: 500, tracking: 0.32, upper: true, font: 'body' },
    productNameWeight: 400,
    cardRadius: 0,
    btnRadius: 999,
    showRules: false,
    productPad: 0,
  },
};

window.MIDU_THEMES = MIDU_THEMES;
